/**
 * @author Vijet Badigannavar (bvijet@in.bosch.com)
 */
package com.bezirk.control.messages.streaming;

import com.bezirk.control.messages.ControlMessage;
import com.bezirk.control.messages.UnicastControlMessage;
import com.bezirk.middleware.addressing.Location;
import com.bezirk.proxy.api.impl.BezirkZirkEndPoint;

/**
 * This Message is internally sent by the Bezirk for hand shaking with the recipient.
 */
public class StreamRequest extends UnicastControlMessage {
    /**
     * Discriminator that uniquely defines the Control message!
     */
    private final static Discriminator discriminator = ControlMessage.Discriminator.StreamRequest;
    /**
     * Location that is used for MulticastStream
     */
    public Location location = null;
    /**
     * Contains the serialized String of the Stream Descriptor pushed by the Stream
     */
    public String serialzedString = null;
    /**
     * Stream Topic of the Stream Descriptor
     */
    public String streamLabel = null;
    /**
     * Name of the file that needs to be pushed on the recipient
     */
    public String fileName = null;
    /**
     * Flag indicating secure communication. If true file transfer will be encrypted.
     */
    public boolean isEncrypted = false;
    /**
     * Flag indicating the communication is quantized. If <code>true</code> data  will be quantized
     * and sent
     */
    public boolean isIncremental = false;
    /**
     * Flag indicating isReliable transfer. If <code>false</code>, the communication is unreliable
     */
    public boolean reliable = true;
    /**
     * StreamId generated by the Proxy on corresponding Services
     */
    public short localStreamId = (short) -1;

    public StreamRequest(BezirkZirkEndPoint sender, BezirkZirkEndPoint recipient, String sphereName,
                         String key, Location location, String serialzedString, String streamLabel, String fileName, boolean isEncrypted,
                         boolean isIncremental, boolean reliable, short localStreamId) {
        super(sender, recipient, sphereName, discriminator, false, key);
        this.location = location;
        this.serialzedString = serialzedString;
        this.streamLabel = streamLabel;
        this.fileName = fileName;
        this.isEncrypted = isEncrypted;
        this.isIncremental = isIncremental;
        this.reliable = reliable;
        this.localStreamId = localStreamId;
    }
}
